#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ConditionChecker_AtLeastFinishedGameCount

#include "Basic.hpp"

#include "BP_ConditionChecker_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ConditionChecker_AtLeastFinishedGameCount.BP_ConditionChecker_AtLeastFinishedGameCount_C
// 0x0008 (0x0068 - 0x0060)
class UBP_ConditionChecker_AtLeastFinishedGameCount_C final : public UBP_ConditionChecker_C
{
public:
	int32                                         FinishedGameCount;                                 // 0x0060(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BindEventOnGameStateChanged(const TDelegate<void()>& Event);
	bool CheckInternal();
	void UnbindEventOnGameStateChanged(const TDelegate<void()>& Event);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ConditionChecker_AtLeastFinishedGameCount_C">();
	}
	static class UBP_ConditionChecker_AtLeastFinishedGameCount_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ConditionChecker_AtLeastFinishedGameCount_C>();
	}
};
static_assert(alignof(UBP_ConditionChecker_AtLeastFinishedGameCount_C) == 0x000008, "Wrong alignment on UBP_ConditionChecker_AtLeastFinishedGameCount_C");
static_assert(sizeof(UBP_ConditionChecker_AtLeastFinishedGameCount_C) == 0x000068, "Wrong size on UBP_ConditionChecker_AtLeastFinishedGameCount_C");
static_assert(offsetof(UBP_ConditionChecker_AtLeastFinishedGameCount_C, FinishedGameCount) == 0x000060, "Member 'UBP_ConditionChecker_AtLeastFinishedGameCount_C::FinishedGameCount' has a wrong offset!");

}

