#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Dialogue_Lumiere_ExpFestival_Victor

#include "Basic.hpp"

#include "BP_Dialogue_Lumiere_ExpFestival_Victor_classes.hpp"
#include "BP_Dialogue_Lumiere_ExpFestival_Victor_parameters.hpp"


namespace SDK
{

// Function BP_Dialogue_Lumiere_ExpFestival_Victor.BP_Dialogue_Lumiere_ExpFestival_Victor_C.ExecuteUbergraph_BP_Dialogue_Lumiere_ExpFestival_Victor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_Lumiere_ExpFestival_Victor_C::ExecuteUbergraph_BP_Dialogue_Lumiere_ExpFestival_Victor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_Lumiere_ExpFestival_Victor_C", "ExecuteUbergraph_BP_Dialogue_Lumiere_ExpFestival_Victor");

	Params::BP_Dialogue_Lumiere_ExpFestival_Victor_C_ExecuteUbergraph_BP_Dialogue_Lumiere_ExpFestival_Victor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Dialogue_Lumiere_ExpFestival_Victor.BP_Dialogue_Lumiere_ExpFestival_Victor_C.StartDialog
// (BlueprintCallable, BlueprintEvent)

void ABP_Dialogue_Lumiere_ExpFestival_Victor_C::StartDialog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_Lumiere_ExpFestival_Victor_C", "StartDialog");

	UObject::ProcessEvent(Func, nullptr);
}

}

