#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DialogueCamp_Empty

#include "Basic.hpp"

#include "BP_Dialogue_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DialogueCamp_Empty.BP_DialogueCamp_Empty_C
// 0x0008 (0x0340 - 0x0338)
class ABP_DialogueCamp_Empty_C final : public ABP_Dialogue_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_DialogueCamp_Empty_C;            // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_DialogueCamp_Empty(int32 EntryPoint);
	void StartDialog();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DialogueCamp_Empty_C">();
	}
	static class ABP_DialogueCamp_Empty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DialogueCamp_Empty_C>();
	}
};
static_assert(alignof(ABP_DialogueCamp_Empty_C) == 0x000008, "Wrong alignment on ABP_DialogueCamp_Empty_C");
static_assert(sizeof(ABP_DialogueCamp_Empty_C) == 0x000340, "Wrong size on ABP_DialogueCamp_Empty_C");
static_assert(offsetof(ABP_DialogueCamp_Empty_C, UberGraphFrame_BP_DialogueCamp_Empty_C) == 0x000338, "Member 'ABP_DialogueCamp_Empty_C::UberGraphFrame_BP_DialogueCamp_Empty_C' has a wrong offset!");

}

