#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameActionInstance_ForceNPCDialogue

#include "Basic.hpp"

#include "BP_GameActionInstance_ForceNPCDialogue_classes.hpp"
#include "BP_GameActionInstance_ForceNPCDialogue_parameters.hpp"


namespace SDK
{

// Function BP_GameActionInstance_ForceNPCDialogue.BP_GameActionInstance_ForceNPCDialogue_C.ExecuteGameAction
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class APlayerController*          Controller                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_GameActionInstance_ForceNPCDialogue_C::ExecuteGameAction(const class APlayerController* Controller)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameActionInstance_ForceNPCDialogue_C", "ExecuteGameAction");

	Params::BP_GameActionInstance_ForceNPCDialogue_C_ExecuteGameAction Parms{};

	Parms.Controller = Controller;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameActionInstance_ForceNPCDialogue.BP_GameActionInstance_ForceNPCDialogue_C.ExecuteUbergraph_BP_GameActionInstance_ForceNPCDialogue
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GameActionInstance_ForceNPCDialogue_C::ExecuteUbergraph_BP_GameActionInstance_ForceNPCDialogue(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameActionInstance_ForceNPCDialogue_C", "ExecuteUbergraph_BP_GameActionInstance_ForceNPCDialogue");

	Params::BP_GameActionInstance_ForceNPCDialogue_C_ExecuteUbergraph_BP_GameActionInstance_ForceNPCDialogue Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameActionInstance_ForceNPCDialogue.BP_GameActionInstance_ForceNPCDialogue_C.GetDialogueSettings
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_jRPG_NPC_Dialog_C**           NPCDialog                                              (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FS_DialogueParameters*           DialogueParameters                                     (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_GameActionInstance_ForceNPCDialogue_C::GetDialogueSettings(class ABP_jRPG_NPC_Dialog_C** NPCDialog, struct FS_DialogueParameters* DialogueParameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameActionInstance_ForceNPCDialogue_C", "GetDialogueSettings");

	Params::BP_GameActionInstance_ForceNPCDialogue_C_GetDialogueSettings Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NPCDialog != nullptr)
		*NPCDialog = Parms.NPCDialog;

	if (DialogueParameters != nullptr)
		*DialogueParameters = std::move(Parms.DialogueParameters);
}


// Function BP_GameActionInstance_ForceNPCDialogue.BP_GameActionInstance_ForceNPCDialogue_C.OnDialogueFinished
// (BlueprintCallable, BlueprintEvent)

void UBP_GameActionInstance_ForceNPCDialogue_C::OnDialogueFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameActionInstance_ForceNPCDialogue_C", "OnDialogueFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameActionInstance_ForceNPCDialogue.BP_GameActionInstance_ForceNPCDialogue_C.GetDebugString
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UBP_GameActionInstance_ForceNPCDialogue_C::GetDebugString() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameActionInstance_ForceNPCDialogue_C", "GetDebugString");

	Params::BP_GameActionInstance_ForceNPCDialogue_C_GetDebugString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

