#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GPE_Manor_Piano

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FPromptParams_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "E_CharacterList_structs.hpp"


namespace SDK::Params
{

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// 0x0118 (0x0118 - 0x0000)
struct BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x00F8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature) == 0x000118, "Wrong size on BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature) == 0x000020, "Wrong size on BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_GPE_Manor_Piano_C_BndEvt__BP_GPE_Manor_Piano_InteractionRange_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.ExecuteUbergraph_BP_GPE_Manor_Piano
// 0x0498 (0x0498 - 0x0000)
struct BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded_4;                       // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable;                              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             K2Node_DynamicCast_AsSound_Base;                   // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_CharacterList                               Temp_byte_Variable;                                // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class USoundBase*>                     Temp_object_Variable_1;                            // 0x0028(0x0010)(ReferenceParm)
	class UObject*                                K2Node_CustomEvent_Loaded_3;                       // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_2;                            // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             K2Node_DynamicCast_AsSound_Base_1;                 // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded_2;                       // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_3;                            // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             K2Node_DynamicCast_AsSound_Base_2;                 // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded_1;                       // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_4;                            // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             K2Node_DynamicCast_AsSound_Base_3;                 // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded;                         // 0x0098(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_5;                            // 0x00A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             K2Node_DynamicCast_AsSound_Base_4;                 // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x3];                                       // 0x00B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate;              // 0x00C4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UObject*                                Temp_object_Variable_6;                            // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             K2Node_DynamicCast_AsSound_Base_5;                 // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_CustomEvent_Loaded_5;                       // 0x0110(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_1;            // 0x011C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_jRPG_Character_World_C*             K2Node_Event_InteractingWorldCharacter;            // 0x0140(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_Instant;                              // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14A[0x6];                                      // 0x014A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0150(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_jRPG_GI_Custom_C*                   K2Node_DynamicCast_AsBP_J_RPG_GI_Custom;           // 0x0158(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x0160(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_CharacterList                               CallFunc_GetCurrentCharacterWorld_CurrentCharacterWorldEnum; // 0x0161(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_162[0x2];                                      // 0x0162(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0164(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundBase>              CallFunc_Array_Get_Item;                           // 0x0170(0x0028)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0198(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x019C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19D[0x3];                                      // 0x019D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_2;            // 0x01A0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class USoundBase>              CallFunc_Array_Get_Item_1;                         // 0x01B8(0x0028)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x01E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x01E4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E5[0x3];                                      // 0x01E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x01E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_3;            // 0x0200(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class USoundBase>              CallFunc_Array_Get_Item_2;                         // 0x0210(0x0028)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x023C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_241[0x3];                                      // 0x0241(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_4;            // 0x0244(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundBase>              CallFunc_Array_Get_Item_3;                         // 0x0258(0x0028)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0280(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0284(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_285[0x3];                                      // 0x0285(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class USoundBase>              CallFunc_Array_Get_Item_4;                         // 0x0288(0x0028)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x02B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x02B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B5[0x3];                                      // 0x02B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_3;                  // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_4;                  // 0x02BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* Loaded)>        K2Node_CreateDelegate_OutputDelegate_5;            // 0x02C0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class USoundBase>              CallFunc_Array_Get_Item_5;                         // 0x02D0(0x0028)(HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x02FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FD[0x3];                                      // 0x02FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue_5;                  // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent_1;  // 0x0308(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor_1;           // 0x0310(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp_1;            // 0x0318(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex_1;       // 0x0320(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x0324(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_325[0x3];                                      // 0x0325(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0328(0x00F8)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0420(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0428(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0430(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0438(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43C[0x4];                                      // 0x043C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0440(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_jRPG_GI_Custom_C*                   CallFunc_GetCustomGI_ReturnValue;                  // 0x0448(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0450(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_451[0x7];                                      // 0x0451(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue_1;              // 0x0458(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_jRPG_GI_Custom_C*                   CallFunc_GetCustomGI_ReturnValue_1;                // 0x0460(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0468(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_469[0x7];                                      // 0x0469(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class USoundBase*>                     K2Node_Select_Default;                             // 0x0470(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_6;               // 0x0480(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue;               // 0x0484(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Percent_IntInt_ReturnValue_1;             // 0x0488(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_48C[0x4];                                      // 0x048C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             CallFunc_Array_Get_Item_6;                         // 0x0490(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano");
static_assert(sizeof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano) == 0x000498, "Wrong size on BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, EntryPoint) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CustomEvent_Loaded_4) == 0x000008, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CustomEvent_Loaded_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_object_Variable) == 0x000010, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_AsSound_Base) == 0x000018, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_AsSound_Base' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_byte_Variable) == 0x000021, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_object_Variable_1) == 0x000028, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CustomEvent_Loaded_3) == 0x000038, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CustomEvent_Loaded_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_object_Variable_2) == 0x000040, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_AsSound_Base_1) == 0x000048, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_AsSound_Base_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CustomEvent_Loaded_2) == 0x000058, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CustomEvent_Loaded_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_object_Variable_3) == 0x000060, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_AsSound_Base_2) == 0x000068, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_AsSound_Base_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_bSuccess_2) == 0x000070, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CustomEvent_Loaded_1) == 0x000078, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CustomEvent_Loaded_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_object_Variable_4) == 0x000080, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_object_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_AsSound_Base_3) == 0x000088, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_AsSound_Base_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_bSuccess_3) == 0x000090, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CustomEvent_Loaded) == 0x000098, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CustomEvent_Loaded' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_object_Variable_5) == 0x0000A0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_object_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_AsSound_Base_4) == 0x0000A8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_AsSound_Base_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_bSuccess_4) == 0x0000B0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Array_Index_Variable) == 0x0000B4, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Loop_Counter_Variable) == 0x0000B8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Add_IntInt_ReturnValue) == 0x0000BC, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Loop_Counter_Variable_1) == 0x0000C0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CreateDelegate_OutputDelegate) == 0x0000C4, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000D4, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_object_Variable_6) == 0x0000D8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_object_Variable_6' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Loop_Counter_Variable_2) == 0x0000E0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_AsSound_Base_5) == 0x0000E8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_AsSound_Base_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_bSuccess_5) == 0x0000F0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000F4, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Array_Index_Variable_1) == 0x0000F8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Array_Index_Variable_2) == 0x0000FC, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Loop_Counter_Variable_3) == 0x000100, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Add_IntInt_ReturnValue_3) == 0x000104, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Array_Index_Variable_3) == 0x000108, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CustomEvent_Loaded_5) == 0x000110, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CustomEvent_Loaded_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Loop_Counter_Variable_4) == 0x000118, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CreateDelegate_OutputDelegate_1) == 0x00011C, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Add_IntInt_ReturnValue_4) == 0x00012C, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Loop_Counter_Variable_5) == 0x000130, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Add_IntInt_ReturnValue_5) == 0x000134, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Array_Index_Variable_4) == 0x000138, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, Temp_int_Array_Index_Variable_5) == 0x00013C, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_Event_InteractingWorldCharacter) == 0x000140, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_Event_InteractingWorldCharacter' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_Event_Instant) == 0x000148, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_Event_Instant' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_IsValid_ReturnValue) == 0x000149, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_GetGameInstance_ReturnValue) == 0x000150, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_AsBP_J_RPG_GI_Custom) == 0x000158, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_AsBP_J_RPG_GI_Custom' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_DynamicCast_bSuccess_6) == 0x000160, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_GetCurrentCharacterWorld_CurrentCharacterWorldEnum) == 0x000161, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_GetCurrentCharacterWorld_CurrentCharacterWorldEnum' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Add_IntInt_ReturnValue_6) == 0x000164, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000168, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Get_Item) == 0x000170, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Length_ReturnValue) == 0x000198, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Less_IntInt_ReturnValue) == 0x00019C, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CreateDelegate_OutputDelegate_2) == 0x0001A0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Add_ReturnValue) == 0x0001B0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Add_ReturnValue_1) == 0x0001B4, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Get_Item_1) == 0x0001B8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Length_ReturnValue_1) == 0x0001E0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Less_IntInt_ReturnValue_1) == 0x0001E4, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x0001E8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CreateDelegate_OutputDelegate_3) == 0x000200, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Get_Item_2) == 0x000210, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Add_ReturnValue_2) == 0x000238, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Add_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Length_ReturnValue_2) == 0x00023C, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Less_IntInt_ReturnValue_2) == 0x000240, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CreateDelegate_OutputDelegate_4) == 0x000244, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Get_Item_3) == 0x000258, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Length_ReturnValue_3) == 0x000280, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Less_IntInt_ReturnValue_3) == 0x000284, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Get_Item_4) == 0x000288, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Length_ReturnValue_4) == 0x0002B0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Less_IntInt_ReturnValue_4) == 0x0002B4, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Add_ReturnValue_3) == 0x0002B8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Add_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Add_ReturnValue_4) == 0x0002BC, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Add_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_CreateDelegate_OutputDelegate_5) == 0x0002C0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Get_Item_5) == 0x0002D0, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Length_ReturnValue_5) == 0x0002F8, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Less_IntInt_ReturnValue_5) == 0x0002FC, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Add_ReturnValue_5) == 0x000300, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Add_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OverlappedComponent_1) == 0x000308, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OverlappedComponent_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OtherActor_1) == 0x000310, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OtherActor_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OtherComp_1) == 0x000318, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OtherComp_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OtherBodyIndex_1) == 0x000320, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OtherBodyIndex_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_bFromSweep) == 0x000324, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_SweepResult) == 0x000328, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000420, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OtherActor) == 0x000428, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OtherComp) == 0x000430, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000438, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_GetPlayerPawn_ReturnValue) == 0x000440, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_GetCustomGI_ReturnValue) == 0x000448, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_GetCustomGI_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000450, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_GetPlayerPawn_ReturnValue_1) == 0x000458, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_GetPlayerPawn_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_GetCustomGI_ReturnValue_1) == 0x000460, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_GetCustomGI_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000468, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, K2Node_Select_Default) == 0x000470, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Length_ReturnValue_6) == 0x000480, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Length_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Percent_IntInt_ReturnValue) == 0x000484, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Percent_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Percent_IntInt_ReturnValue_1) == 0x000488, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Percent_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano, CallFunc_Array_Get_Item_6) == 0x000490, "Member 'BP_GPE_Manor_Piano_C_ExecuteUbergraph_BP_GPE_Manor_Piano::CallFunc_Array_Get_Item_6' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.GetInteractionPromptParams
// 0x0018 (0x0018 - 0x0000)
struct BP_GPE_Manor_Piano_C_GetInteractionPromptParams final
{
public:
	struct FFPromptParams                         PromptParams;                                      // 0x0000(0x0018)(Parm, OutParm, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_GetInteractionPromptParams) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_GetInteractionPromptParams");
static_assert(sizeof(BP_GPE_Manor_Piano_C_GetInteractionPromptParams) == 0x000018, "Wrong size on BP_GPE_Manor_Piano_C_GetInteractionPromptParams");
static_assert(offsetof(BP_GPE_Manor_Piano_C_GetInteractionPromptParams, PromptParams) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_GetInteractionPromptParams::PromptParams' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.OnInteractionRequested
// 0x0010 (0x0010 - 0x0000)
struct BP_GPE_Manor_Piano_C_OnInteractionRequested final
{
public:
	class ABP_jRPG_Character_World_C*             InteractingWorldCharacter;                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Instant;                                           // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_OnInteractionRequested) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_OnInteractionRequested");
static_assert(sizeof(BP_GPE_Manor_Piano_C_OnInteractionRequested) == 0x000010, "Wrong size on BP_GPE_Manor_Piano_C_OnInteractionRequested");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnInteractionRequested, InteractingWorldCharacter) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_OnInteractionRequested::InteractingWorldCharacter' has a wrong offset!");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnInteractionRequested, Instant) == 0x000008, "Member 'BP_GPE_Manor_Piano_C_OnInteractionRequested::Instant' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.OnLoaded_15640CA4409829B0685D7299A24C68A5
// 0x0008 (0x0008 - 0x0000)
struct BP_GPE_Manor_Piano_C_OnLoaded_15640CA4409829B0685D7299A24C68A5 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_OnLoaded_15640CA4409829B0685D7299A24C68A5) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_OnLoaded_15640CA4409829B0685D7299A24C68A5");
static_assert(sizeof(BP_GPE_Manor_Piano_C_OnLoaded_15640CA4409829B0685D7299A24C68A5) == 0x000008, "Wrong size on BP_GPE_Manor_Piano_C_OnLoaded_15640CA4409829B0685D7299A24C68A5");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnLoaded_15640CA4409829B0685D7299A24C68A5, Loaded) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_OnLoaded_15640CA4409829B0685D7299A24C68A5::Loaded' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95
// 0x0008 (0x0008 - 0x0000)
struct BP_GPE_Manor_Piano_C_OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95");
static_assert(sizeof(BP_GPE_Manor_Piano_C_OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95) == 0x000008, "Wrong size on BP_GPE_Manor_Piano_C_OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95, Loaded) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_OnLoaded_4EA72A634348FE9FE4B6EEB63C138D95::Loaded' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.OnLoaded_7E2BE2744DE404D87B7316AD8031D202
// 0x0008 (0x0008 - 0x0000)
struct BP_GPE_Manor_Piano_C_OnLoaded_7E2BE2744DE404D87B7316AD8031D202 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_OnLoaded_7E2BE2744DE404D87B7316AD8031D202) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_OnLoaded_7E2BE2744DE404D87B7316AD8031D202");
static_assert(sizeof(BP_GPE_Manor_Piano_C_OnLoaded_7E2BE2744DE404D87B7316AD8031D202) == 0x000008, "Wrong size on BP_GPE_Manor_Piano_C_OnLoaded_7E2BE2744DE404D87B7316AD8031D202");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnLoaded_7E2BE2744DE404D87B7316AD8031D202, Loaded) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_OnLoaded_7E2BE2744DE404D87B7316AD8031D202::Loaded' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8
// 0x0008 (0x0008 - 0x0000)
struct BP_GPE_Manor_Piano_C_OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8");
static_assert(sizeof(BP_GPE_Manor_Piano_C_OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8) == 0x000008, "Wrong size on BP_GPE_Manor_Piano_C_OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8, Loaded) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_OnLoaded_8DE66D2D4C811D5DA38BF9875502AEB8::Loaded' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0
// 0x0008 (0x0008 - 0x0000)
struct BP_GPE_Manor_Piano_C_OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0");
static_assert(sizeof(BP_GPE_Manor_Piano_C_OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0) == 0x000008, "Wrong size on BP_GPE_Manor_Piano_C_OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0, Loaded) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_OnLoaded_B916CACA4E1BA09B227D539BC97D4EF0::Loaded' has a wrong offset!");

// Function BP_GPE_Manor_Piano.BP_GPE_Manor_Piano_C.OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8
// 0x0008 (0x0008 - 0x0000)
struct BP_GPE_Manor_Piano_C_OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8 final
{
public:
	class UObject*                                Loaded;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_GPE_Manor_Piano_C_OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8) == 0x000008, "Wrong alignment on BP_GPE_Manor_Piano_C_OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8");
static_assert(sizeof(BP_GPE_Manor_Piano_C_OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8) == 0x000008, "Wrong size on BP_GPE_Manor_Piano_C_OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8");
static_assert(offsetof(BP_GPE_Manor_Piano_C_OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8, Loaded) == 0x000000, "Member 'BP_GPE_Manor_Piano_C_OnLoaded_D0F488884D2906867D0CCDAF2B2A04C8::Loaded' has a wrong offset!");

}

