#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameAction_SetEnableAutoSave

#include "Basic.hpp"

#include "BP_PDT_GameAction_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameAction_SetEnableAutoSave.BP_GameAction_SetEnableAutoSave_C
// 0x0008 (0x0038 - 0x0030)
class UBP_GameAction_SetEnableAutoSave_C final : public UBP_PDT_GameAction_C
{
public:
	bool                                          EnableAutoSave;                                    // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	TSubclassOf<class UGameActionInstance> GetInstanceClass();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GameAction_SetEnableAutoSave_C">();
	}
	static class UBP_GameAction_SetEnableAutoSave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GameAction_SetEnableAutoSave_C>();
	}
};
static_assert(alignof(UBP_GameAction_SetEnableAutoSave_C) == 0x000008, "Wrong alignment on UBP_GameAction_SetEnableAutoSave_C");
static_assert(sizeof(UBP_GameAction_SetEnableAutoSave_C) == 0x000038, "Wrong size on UBP_GameAction_SetEnableAutoSave_C");
static_assert(offsetof(UBP_GameAction_SetEnableAutoSave_C, EnableAutoSave) == 0x000030, "Member 'UBP_GameAction_SetEnableAutoSave_C::EnableAutoSave' has a wrong offset!");

}

