#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameActionTriggerZone_Sphere

#include "Basic.hpp"

#include "BP_GameActionTriggerZone_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameActionTriggerZone_Sphere.BP_GameActionTriggerZone_Sphere_C
// 0x0008 (0x0338 - 0x0330)
class ABP_GameActionTriggerZone_Sphere_C final : public ABP_GameActionTriggerZone_C
{
public:
	class USphereComponent*                       TriggerSphere;                                     // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GameActionTriggerZone_Sphere_C">();
	}
	static class ABP_GameActionTriggerZone_Sphere_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GameActionTriggerZone_Sphere_C>();
	}
};
static_assert(alignof(ABP_GameActionTriggerZone_Sphere_C) == 0x000008, "Wrong alignment on ABP_GameActionTriggerZone_Sphere_C");
static_assert(sizeof(ABP_GameActionTriggerZone_Sphere_C) == 0x000338, "Wrong size on ABP_GameActionTriggerZone_Sphere_C");
static_assert(offsetof(ABP_GameActionTriggerZone_Sphere_C, TriggerSphere) == 0x000330, "Member 'ABP_GameActionTriggerZone_Sphere_C::TriggerSphere' has a wrong offset!");

}

