#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameAction_AddItemToInventory

#include "Basic.hpp"

#include "S_LootContext_structs.hpp"
#include "S_ItemOperationData_structs.hpp"
#include "BP_PDT_GameAction_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameAction_AddItemToInventory.BP_GameAction_AddItemToInventory_C
// 0x0018 (0x0048 - 0x0030)
class UBP_GameAction_AddItemToInventory_C final : public UBP_PDT_GameAction_C
{
public:
	TArray<struct FS_ItemOperationData>           Items;                                             // 0x0030(0x0010)(Edit, BlueprintVisible)
	struct FS_LootContext                         LootContext;                                       // 0x0040(0x0004)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	TSubclassOf<class UGameActionInstance> GetInstanceClass();
	void ValidateGameAction(TArray<class FText>& ErrorMessages, class FString& PropertyPath, bool& ExploreAssetChildren);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_GameAction_AddItemToInventory_C">();
	}
	static class UBP_GameAction_AddItemToInventory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GameAction_AddItemToInventory_C>();
	}
};
static_assert(alignof(UBP_GameAction_AddItemToInventory_C) == 0x000008, "Wrong alignment on UBP_GameAction_AddItemToInventory_C");
static_assert(sizeof(UBP_GameAction_AddItemToInventory_C) == 0x000048, "Wrong size on UBP_GameAction_AddItemToInventory_C");
static_assert(offsetof(UBP_GameAction_AddItemToInventory_C, Items) == 0x000030, "Member 'UBP_GameAction_AddItemToInventory_C::Items' has a wrong offset!");
static_assert(offsetof(UBP_GameAction_AddItemToInventory_C, LootContext) == 0x000040, "Member 'UBP_GameAction_AddItemToInventory_C::LootContext' has a wrong offset!");

}

