#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female

#include "Basic.hpp"

#include "BP_jRPG_NPC_Dialog_NPCLumiere_Citizen1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female.BP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C
// 0x0000 (0x0BD0 - 0x0BD0)
class ABP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C final : public ABP_jRPG_NPC_Dialog_NPCLumiere_Citizen1_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C">();
	}
	static class ABP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C>();
	}
};
static_assert(alignof(ABP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C) == 0x000010, "Wrong alignment on ABP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C");
static_assert(sizeof(ABP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C) == 0x000BD0, "Wrong size on ABP_JRPG_NPC_Dialog_NPC_Lumiere_Teen_female_C");

}

