#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene

#include "Basic.hpp"

#include "BP_jRPG_NPC_Dialog_NPCLumiere_Citizen1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene.BP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C
// 0x0000 (0x0BD0 - 0x0BD0)
class ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C final : public ABP_jRPG_NPC_Dialog_NPCLumiere_Citizen1_C
{
public:
	uint8                                         Pad_BC1[0x7];                                      // 0x0BC1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   SM_FlowerNeckLace_OnCharacter_A_01;                // 0x0BC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C">();
	}
	static class ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C>();
	}
};
static_assert(alignof(ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C) == 0x000010, "Wrong alignment on ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C");
static_assert(sizeof(ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C) == 0x000BD0, "Wrong size on ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C");
static_assert(offsetof(ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C, SM_FlowerNeckLace_OnCharacter_A_01) == 0x000BC8, "Member 'ABP_JRPG_NPC_Dialog_NPC_Lumiere_Eugene_C::SM_FlowerNeckLace_OnCharacter_A_01' has a wrong offset!");

}

