#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_jRPG_NPC_Dialog_Human_ManyCams

#include "Basic.hpp"

#include "BP_jRPG_NPC_Dialog_Human_ManyCams_classes.hpp"
#include "BP_jRPG_NPC_Dialog_Human_ManyCams_parameters.hpp"


namespace SDK
{

// Function BP_jRPG_NPC_Dialog_Human_ManyCams.BP_jRPG_NPC_Dialog_Human_ManyCams_C.BPI_GetDialogueCameraByType
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EDialogueCameraType                     CameraType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UCameraComponent**                CameraComponent                                        (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_jRPG_NPC_Dialog_Human_ManyCams_C::BPI_GetDialogueCameraByType(EDialogueCameraType CameraType, class UCameraComponent** CameraComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_jRPG_NPC_Dialog_Human_ManyCams_C", "BPI_GetDialogueCameraByType");

	Params::BP_jRPG_NPC_Dialog_Human_ManyCams_C_BPI_GetDialogueCameraByType Parms{};

	Parms.CameraType = CameraType;

	UObject::ProcessEvent(Func, &Parms);

	if (CameraComponent != nullptr)
		*CameraComponent = Parms.CameraComponent;
}


// Function BP_jRPG_NPC_Dialog_Human_ManyCams.BP_jRPG_NPC_Dialog_Human_ManyCams_C.GetAllDialogueCameras
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UCineCameraComponent*>*    Array                                                  (Parm, OutParm, ContainsInstancedReference)

void ABP_jRPG_NPC_Dialog_Human_ManyCams_C::GetAllDialogueCameras(TArray<class UCineCameraComponent*>* Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_jRPG_NPC_Dialog_Human_ManyCams_C", "GetAllDialogueCameras");

	Params::BP_jRPG_NPC_Dialog_Human_ManyCams_C_GetAllDialogueCameras Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Array != nullptr)
		*Array = std::move(Parms.Array);
}

}

