#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Monolith

#include "Basic.hpp"

#include "BP_Monolith_classes.hpp"
#include "BP_Monolith_parameters.hpp"


namespace SDK
{

// Function BP_Monolith.BP_Monolith_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Monolith_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Monolith_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Monolith.BP_Monolith_C.RefreshMonolith
// (BlueprintCallable, BlueprintEvent)

void ABP_Monolith_C::RefreshMonolith()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Monolith_C", "RefreshMonolith");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Monolith.BP_Monolith_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Monolith_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Monolith_C", "ReceiveTick");

	Params::BP_Monolith_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Monolith.BP_Monolith_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Monolith_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Monolith_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Monolith.BP_Monolith_C.ExecuteUbergraph_BP_Monolith
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Monolith_C::ExecuteUbergraph_BP_Monolith(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Monolith_C", "ExecuteUbergraph_BP_Monolith");

	Params::BP_Monolith_C_ExecuteUbergraph_BP_Monolith Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

