#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto

#include "Basic.hpp"

#include "BP_NPCs_Lumiere_Adult_Male_3_Michel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto.BP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C
// 0x0008 (0x0300 - 0x02F8)
class ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C final : public ABP_NPCs_Lumiere_Adult_Male_3_Michel_C
{
public:
	class UStaticMeshComponent*                   Photo;                                             // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C">();
	}
	static class ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C>();
	}
};
static_assert(alignof(ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C) == 0x000008, "Wrong alignment on ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C");
static_assert(sizeof(ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C) == 0x000300, "Wrong size on ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C");
static_assert(offsetof(ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C, Photo) == 0x0002F8, "Member 'ABP_NPCs_Lumiere_Adult_Male_3_Michel_HoldPhoto_C::Photo' has a wrong offset!");

}

