#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPCs_Lumiere

#include "Basic.hpp"

#include "BP_NPCs_Lumiere_classes.hpp"
#include "BP_NPCs_Lumiere_parameters.hpp"


namespace SDK
{

// Function BP_NPCs_Lumiere.BP_NPCs_Lumiere_C.ActivateFX
// (BlueprintCallable, BlueprintEvent)

void ABP_NPCs_Lumiere_C::ActivateFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCs_Lumiere_C", "ActivateFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPCs_Lumiere.BP_NPCs_Lumiere_C.ExecuteUbergraph_BP_NPCs_Lumiere
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPCs_Lumiere_C::ExecuteUbergraph_BP_NPCs_Lumiere(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCs_Lumiere_C", "ExecuteUbergraph_BP_NPCs_Lumiere");

	Params::BP_NPCs_Lumiere_C_ExecuteUbergraph_BP_NPCs_Lumiere Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPCs_Lumiere.BP_NPCs_Lumiere_C.GetAllElementsToDust
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UMeshComponent*>*          ElementsToDust                                         (Parm, OutParm, ContainsInstancedReference)

void ABP_NPCs_Lumiere_C::GetAllElementsToDust(TArray<class UMeshComponent*>* ElementsToDust)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCs_Lumiere_C", "GetAllElementsToDust");

	Params::BP_NPCs_Lumiere_C_GetAllElementsToDust Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ElementsToDust != nullptr)
		*ElementsToDust = std::move(Parms.ElementsToDust);
}


// Function BP_NPCs_Lumiere.BP_NPCs_Lumiere_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_NPCs_Lumiere_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCs_Lumiere_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPCs_Lumiere.BP_NPCs_Lumiere_C.ResetFX
// (BlueprintCallable, BlueprintEvent)

void ABP_NPCs_Lumiere_C::ResetFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCs_Lumiere_C", "ResetFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPCs_Lumiere.BP_NPCs_Lumiere_C.SetDustingLevel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPCs_Lumiere_C::SetDustingLevel(double NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCs_Lumiere_C", "SetDustingLevel");

	Params::BP_NPCs_Lumiere_C_SetDustingLevel Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPCs_Lumiere.BP_NPCs_Lumiere_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_NPCs_Lumiere_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPCs_Lumiere_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

