#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Particle_Fireflies

#include "Basic.hpp"

#include "BP_Particle_Fireflies_classes.hpp"
#include "BP_Particle_Fireflies_parameters.hpp"


namespace SDK
{

// Function BP_Particle_Fireflies.BP_Particle_Fireflies_C.ExecuteUbergraph_BP_Particle_Fireflies
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Particle_Fireflies_C::ExecuteUbergraph_BP_Particle_Fireflies(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Particle_Fireflies_C", "ExecuteUbergraph_BP_Particle_Fireflies");

	Params::BP_Particle_Fireflies_C_ExecuteUbergraph_BP_Particle_Fireflies Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Particle_Fireflies.BP_Particle_Fireflies_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Particle_Fireflies_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Particle_Fireflies_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Particle_Fireflies.BP_Particle_Fireflies_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Particle_Fireflies_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Particle_Fireflies_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

