#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SkillDataComponent_ForetellMechanic

#include "Basic.hpp"

#include "E_UniqueMechanic_Foretell_ChargeType_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function BP_SkillDataComponent_ForetellMechanic.BP_SkillDataComponent_ForetellMechanic_C.CanSkillEngageTwilight
// 0x0038 (0x0038 - 0x0000)
struct BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight final
{
public:
	class UAC_jRPG_CharacterBattleStats_C*        CharacterStats;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          Temp_byte_Variable;                                // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          Temp_byte_Variable_1;                              // 0x0018(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_UniqueMechanic_Foretell_Component_C* CallFunc_GetComponentByClass_ReturnValue;         // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          Temp_byte_Variable_2;                              // 0x0028(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          Temp_byte_Variable_3;                              // 0x0029(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          Temp_byte_Variable_4;                              // 0x002A(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          K2Node_Select_Default;                             // 0x002B(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChargeCount_ReturnValue;               // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight) == 0x000008, "Wrong alignment on BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight");
static_assert(sizeof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight) == 0x000038, "Wrong size on BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, CharacterStats) == 0x000000, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::CharacterStats' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, ReturnValue) == 0x000008, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, Temp_byte_Variable) == 0x000009, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, CallFunc_GetOwner_ReturnValue) == 0x000010, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, Temp_byte_Variable_1) == 0x000018, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, CallFunc_GetComponentByClass_ReturnValue) == 0x000020, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, Temp_byte_Variable_2) == 0x000028, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, Temp_byte_Variable_3) == 0x000029, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, Temp_byte_Variable_4) == 0x00002A, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, K2Node_Select_Default) == 0x00002B, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, CallFunc_GetChargeCount_ReturnValue) == 0x00002C, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::CallFunc_GetChargeCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000030, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight, CallFunc_Greater_IntInt_ReturnValue) == 0x000031, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CanSkillEngageTwilight::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function BP_SkillDataComponent_ForetellMechanic.BP_SkillDataComponent_ForetellMechanic_C.CheckCharacterHasAnyBuffs
// 0x0068 (0x0068 - 0x0000)
struct BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs final
{
public:
	class UAC_jRPG_CharacterBattleStats_C*        CharacterStats;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<TSoftClassPtr<class UClass>>           Buffs;                                             // 0x0008(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_BattleBuffInstanceWrapper_C*        CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 CallFunc_GetObjectClass_ReturnValue;               // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   CallFunc_Conv_ClassToSoftClassReference_ReturnValue; // 0x0038(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62[0x2];                                       // 0x0062(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs) == 0x000008, "Wrong alignment on BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs");
static_assert(sizeof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs) == 0x000068, "Wrong size on BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CharacterStats) == 0x000000, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CharacterStats' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, Buffs) == 0x000008, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::Buffs' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, ReturnValue) == 0x000018, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CallFunc_Array_Get_Item) == 0x000020, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, Temp_int_Loop_Counter_Variable) == 0x00002C, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CallFunc_GetObjectClass_ReturnValue) == 0x000030, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CallFunc_GetObjectClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CallFunc_Conv_ClassToSoftClassReference_ReturnValue) == 0x000038, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CallFunc_Conv_ClassToSoftClassReference_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CallFunc_Less_IntInt_ReturnValue) == 0x000060, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CallFunc_Array_Contains_ReturnValue) == 0x000061, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs, CallFunc_Add_IntInt_ReturnValue) == 0x000064, "Member 'BP_SkillDataComponent_ForetellMechanic_C_CheckCharacterHasAnyBuffs::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function BP_SkillDataComponent_ForetellMechanic.BP_SkillDataComponent_ForetellMechanic_C.GetAnyForetellCount
// 0x0008 (0x0008 - 0x0000)
struct BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount final
{
public:
	int32                                         ForetellCount;                                     // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount) == 0x000004, "Wrong alignment on BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount");
static_assert(sizeof(BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount) == 0x000008, "Wrong size on BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount, ForetellCount) == 0x000000, "Member 'BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount::ForetellCount' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount, CallFunc_Greater_IntInt_ReturnValue) == 0x000004, "Member 'BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000005, "Member 'BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount, CallFunc_Greater_IntInt_ReturnValue_2) == 0x000006, "Member 'BP_SkillDataComponent_ForetellMechanic_C_GetAnyForetellCount::CallFunc_Greater_IntInt_ReturnValue_2' has a wrong offset!");

// Function BP_SkillDataComponent_ForetellMechanic.BP_SkillDataComponent_ForetellMechanic_C.GetChargeType
// 0x0001 (0x0001 - 0x0000)
struct BP_SkillDataComponent_ForetellMechanic_C_GetChargeType final
{
public:
	E_UniqueMechanic_Foretell_ChargeType          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillDataComponent_ForetellMechanic_C_GetChargeType) == 0x000001, "Wrong alignment on BP_SkillDataComponent_ForetellMechanic_C_GetChargeType");
static_assert(sizeof(BP_SkillDataComponent_ForetellMechanic_C_GetChargeType) == 0x000001, "Wrong size on BP_SkillDataComponent_ForetellMechanic_C_GetChargeType");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_GetChargeType, ReturnValue) == 0x000000, "Member 'BP_SkillDataComponent_ForetellMechanic_C_GetChargeType::ReturnValue' has a wrong offset!");

// Function BP_SkillDataComponent_ForetellMechanic.BP_SkillDataComponent_ForetellMechanic_C.IsOverchargeActive
// 0x0100 (0x0100 - 0x0000)
struct BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive final
{
public:
	class UAC_jRPG_CharacterBattleStats_C*        CharacterStat;                                     // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Active;                                            // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_UniqueMechanic_Foretell_Component_C* local_foretellMechanic;                           // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          local_HasValidCondition;                           // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         local_battleForetellSum;                           // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         local_targetsForetellSum;                          // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UBP_UniqueMechanic_Foretell_Component_C* CallFunc_GetComponentByClass_ReturnValue;         // 0x0030(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanSkillEngageTwilight_ReturnValue;       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAC_jRPG_TargetingManager_C*            CallFunc_GetTargetingManager_ReturnValue;          // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAC_jRPG_TargetingManager_C*            CallFunc_GetTargetingManager_ReturnValue_1;        // 0x0048(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_jRPG_Character_Battle_Base_C*       CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABP_jRPG_Character_Battle_Base_C*> CallFunc_GetAliveEnemies_ReturnValue;            // 0x0068(0x0010)(ReferenceParm)
	class UAC_jRPG_TargetingManager_C*            CallFunc_GetTargetingManager_ReturnValue_2;        // 0x0078(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x009C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x009D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9E[0x2];                                       // 0x009E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_jRPG_Character_Battle_Base_C*       CallFunc_Array_Get_Item_1;                         // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_jRPG_Character_Battle_Base_C*       CallFunc_Array_Get_Item_2;                         // 0x00B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x00C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_jRPG_Character_Battle_Base_C*       CallFunc_Array_Get_Item_3;                         // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetForetellCountOnCharacter_ReturnValue;  // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetForetellCountOnCharacter_ReturnValue_1; // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetForetellCountOnCharacter_ReturnValue_2; // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetForetellCountOnCharacter_ReturnValue_3; // 0x00E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x00EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x00ED(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x00EE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EF[0x1];                                       // 0x00EF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x00F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_6;                // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_3;             // 0x00FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive) == 0x000008, "Wrong alignment on BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive");
static_assert(sizeof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive) == 0x000100, "Wrong size on BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CharacterStat) == 0x000000, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CharacterStat' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Active) == 0x000008, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Active' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, local_foretellMechanic) == 0x000010, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::local_foretellMechanic' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, local_HasValidCondition) == 0x000018, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::local_HasValidCondition' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, local_battleForetellSum) == 0x00001C, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::local_battleForetellSum' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, local_targetsForetellSum) == 0x000020, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::local_targetsForetellSum' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Array_Index_Variable) == 0x000024, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetOwner_ReturnValue) == 0x000028, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetComponentByClass_ReturnValue) == 0x000030, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_CanSkillEngageTwilight_ReturnValue) == 0x000038, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_CanSkillEngageTwilight_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetTargetingManager_ReturnValue) == 0x000040, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetTargetingManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetTargetingManager_ReturnValue_1) == 0x000048, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetTargetingManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Length_ReturnValue) == 0x000050, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Get_Item) == 0x000058, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Length_ReturnValue_1) == 0x000060, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetAliveEnemies_ReturnValue) == 0x000068, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetAliveEnemies_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetTargetingManager_ReturnValue_2) == 0x000078, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetTargetingManager_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Length_ReturnValue_2) == 0x000080, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Loop_Counter_Variable) == 0x000084, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Length_ReturnValue_3) == 0x000088, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Less_IntInt_ReturnValue) == 0x00008C, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Add_IntInt_ReturnValue) == 0x000090, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Loop_Counter_Variable_1) == 0x000094, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Loop_Counter_Variable_2) == 0x000098, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Less_IntInt_ReturnValue_1) == 0x00009C, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Less_IntInt_ReturnValue_2) == 0x00009D, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Add_IntInt_ReturnValue_1) == 0x0000A0, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Add_IntInt_ReturnValue_2) == 0x0000A4, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Array_Index_Variable_1) == 0x0000A8, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Array_Index_Variable_2) == 0x0000AC, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Get_Item_1) == 0x0000B0, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Get_Item_2) == 0x0000B8, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Loop_Counter_Variable_3) == 0x0000C0, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Less_IntInt_ReturnValue_3) == 0x0000C4, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Add_IntInt_ReturnValue_3) == 0x0000C8, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, Temp_int_Array_Index_Variable_3) == 0x0000CC, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Array_Get_Item_3) == 0x0000D0, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetForetellCountOnCharacter_ReturnValue) == 0x0000D8, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetForetellCountOnCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetForetellCountOnCharacter_ReturnValue_1) == 0x0000DC, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetForetellCountOnCharacter_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Greater_IntInt_ReturnValue) == 0x0000E0, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetForetellCountOnCharacter_ReturnValue_2) == 0x0000E4, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetForetellCountOnCharacter_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_GetForetellCountOnCharacter_ReturnValue_3) == 0x0000E8, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_GetForetellCountOnCharacter_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Less_IntInt_ReturnValue_4) == 0x0000EC, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Greater_IntInt_ReturnValue_1) == 0x0000ED, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Less_IntInt_ReturnValue_5) == 0x0000EE, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Add_IntInt_ReturnValue_4) == 0x0000F0, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Add_IntInt_ReturnValue_5) == 0x0000F4, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Less_IntInt_ReturnValue_6) == 0x0000F8, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Less_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Greater_IntInt_ReturnValue_2) == 0x0000F9, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Greater_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive, CallFunc_Greater_IntInt_ReturnValue_3) == 0x0000FA, "Member 'BP_SkillDataComponent_ForetellMechanic_C_IsOverchargeActive::CallFunc_Greater_IntInt_ReturnValue_3' has a wrong offset!");

// Function BP_SkillDataComponent_ForetellMechanic.BP_SkillDataComponent_ForetellMechanic_C.ModifySkillButton
// 0x0120 (0x0120 - 0x0000)
struct BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton final
{
public:
	class UWBP_HUD_SkillButton_Big_C*             SkillButtonWidget;                                 // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanSkillEngageTwilight_ReturnValue;       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable_1;                            // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_2;                            // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 CallFunc_SpawnObject_ReturnValue;                  // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable_3;                            // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          Temp_byte_Variable;                                // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Select_Default;                             // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            CallFunc_MakeBrushFromTexture_ReturnValue;         // 0x0050(0x00D0)()
};
static_assert(alignof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton) == 0x000010, "Wrong alignment on BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton");
static_assert(sizeof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton) == 0x000120, "Wrong size on BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, SkillButtonWidget) == 0x000000, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::SkillButtonWidget' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, Temp_object_Variable) == 0x000008, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, CallFunc_CanSkillEngageTwilight_ReturnValue) == 0x000010, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::CallFunc_CanSkillEngageTwilight_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, Temp_object_Variable_1) == 0x000018, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, Temp_object_Variable_2) == 0x000020, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, CallFunc_SpawnObject_ReturnValue) == 0x000028, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000030, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, Temp_object_Variable_3) == 0x000038, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, Temp_byte_Variable) == 0x000040, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, K2Node_Select_Default) == 0x000048, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton, CallFunc_MakeBrushFromTexture_ReturnValue) == 0x000050, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillButton::CallFunc_MakeBrushFromTexture_ReturnValue' has a wrong offset!");

// Function BP_SkillDataComponent_ForetellMechanic.BP_SkillDataComponent_ForetellMechanic_C.ModifySkillTooltip
// 0x0120 (0x0120 - 0x0000)
struct BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip final
{
public:
	class UWBP_SkillTooltip_C*                    SkillTooltipWidget;                                // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable;                              // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_1;                            // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture2D*                             Temp_object_Variable_2;                            // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 CallFunc_SpawnObject_ReturnValue;                  // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             Temp_object_Variable_3;                            // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	E_UniqueMechanic_Foretell_ChargeType          Temp_byte_Variable;                                // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Select_Default;                             // 0x0040(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_48[0x8];                                       // 0x0048(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            CallFunc_MakeBrushFromTexture_ReturnValue;         // 0x0050(0x00D0)()
};
static_assert(alignof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip) == 0x000010, "Wrong alignment on BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip");
static_assert(sizeof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip) == 0x000120, "Wrong size on BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, SkillTooltipWidget) == 0x000000, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::SkillTooltipWidget' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, Temp_object_Variable) == 0x000008, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, Temp_object_Variable_1) == 0x000010, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, Temp_object_Variable_2) == 0x000018, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, CallFunc_SpawnObject_ReturnValue) == 0x000020, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::CallFunc_SpawnObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000028, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, Temp_object_Variable_3) == 0x000030, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, Temp_byte_Variable) == 0x000038, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, K2Node_Select_Default) == 0x000040, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip, CallFunc_MakeBrushFromTexture_ReturnValue) == 0x000050, "Member 'BP_SkillDataComponent_ForetellMechanic_C_ModifySkillTooltip::CallFunc_MakeBrushFromTexture_ReturnValue' has a wrong offset!");

}

