#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_FluxCameraEvents

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_FluxCameraEvents.BPI_FluxCameraEvents_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_FluxCameraEvents_C final
{
public:
	void FluxCameraInFluid(bool Under);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_FluxCameraEvents_C">();
	}
	static class IBPI_FluxCameraEvents_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_FluxCameraEvents_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_FluxCameraEvents_C) == 0x000001, "Wrong alignment on IBPI_FluxCameraEvents_C");
static_assert(sizeof(IBPI_FluxCameraEvents_C) == 0x000001, "Wrong size on IBPI_FluxCameraEvents_C");

}

