#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_FluxWorldPainter

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_FluxWorldPainter.BPI_FluxWorldPainter_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_FluxWorldPainter_C final
{
public:
	void RenderScenePainter();
	void OnRepaintBrushes();
	void ApplyMaterialParameters(const TArray<class UMaterialInstanceDynamic*>& Materials);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPI_FluxWorldPainter_C">();
	}
	static class IBPI_FluxWorldPainter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_FluxWorldPainter_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
static_assert(alignof(IBPI_FluxWorldPainter_C) == 0x000001, "Wrong alignment on IBPI_FluxWorldPainter_C");
static_assert(sizeof(IBPI_FluxWorldPainter_C) == 0x000001, "Wrong size on IBPI_FluxWorldPainter_C");

}

