#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_UniqueMechanic_Foretell_SkillType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_UniqueMechanic_Foretell_SkillType.E_UniqueMechanic_Foretell_SkillType
// NumValues: 0x0004
enum class E_UniqueMechanic_Foretell_SkillType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	E_UniqueMechanic_Foretell_MAX            = 3,
};

}

