#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EnviroShake_HeavyFootstep

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EnviroShake_HeavyFootstep.EnviroShake_HeavyFootstep_C
// 0x0000 (0x00E0 - 0x00E0)
class UEnviroShake_HeavyFootstep_C final : public UDefaultCameraShakeBase
{
public:
	void NewFunction_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EnviroShake_HeavyFootstep_C">();
	}
	static class UEnviroShake_HeavyFootstep_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEnviroShake_HeavyFootstep_C>();
	}
};
static_assert(alignof(UEnviroShake_HeavyFootstep_C) == 0x000010, "Wrong alignment on UEnviroShake_HeavyFootstep_C");
static_assert(sizeof(UEnviroShake_HeavyFootstep_C) == 0x0000E0, "Wrong size on UEnviroShake_HeavyFootstep_C");

}

