#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Level_Side_TwilightSanctuary

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Level_Side_TwilightSanctuary.Level_Side_TwilightSanctuary_C
// 0x0008 (0x02A0 - 0x0298)
class ALevel_Side_TwilightSanctuary_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Level_Side_TwilightSanctuary(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Level_Side_TwilightSanctuary_C">();
	}
	static class ALevel_Side_TwilightSanctuary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALevel_Side_TwilightSanctuary_C>();
	}
};
static_assert(alignof(ALevel_Side_TwilightSanctuary_C) == 0x000008, "Wrong alignment on ALevel_Side_TwilightSanctuary_C");
static_assert(sizeof(ALevel_Side_TwilightSanctuary_C) == 0x0002A0, "Wrong size on ALevel_Side_TwilightSanctuary_C");
static_assert(offsetof(ALevel_Side_TwilightSanctuary_C, UberGraphFrame) == 0x000298, "Member 'ALevel_Side_TwilightSanctuary_C::UberGraphFrame' has a wrong offset!");

}

