#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_UniqueMechanic_Transform_Masks

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct S_UniqueMechanic_Transform_Masks.S_UniqueMechanic_Transform_Masks
// 0x0020 (0x0020 - 0x0000)
struct FS_UniqueMechanic_Transform_Masks final
{
public:
	class FText                                   MaskName_2_D700A2F840C155E84C36BAB608EF7EDE;       // 0x0000(0x0010)(Edit, BlueprintVisible)
	class FText                                   MaskDescription_4_A41608594B3E8E3813C9B68E0CCD12A5; // 0x0010(0x0010)(Edit, BlueprintVisible)
};
static_assert(alignof(FS_UniqueMechanic_Transform_Masks) == 0x000008, "Wrong alignment on FS_UniqueMechanic_Transform_Masks");
static_assert(sizeof(FS_UniqueMechanic_Transform_Masks) == 0x000020, "Wrong size on FS_UniqueMechanic_Transform_Masks");
static_assert(offsetof(FS_UniqueMechanic_Transform_Masks, MaskName_2_D700A2F840C155E84C36BAB608EF7EDE) == 0x000000, "Member 'FS_UniqueMechanic_Transform_Masks::MaskName_2_D700A2F840C155E84C36BAB608EF7EDE' has a wrong offset!");
static_assert(offsetof(FS_UniqueMechanic_Transform_Masks, MaskDescription_4_A41608594B3E8E3813C9B68E0CCD12A5) == 0x000010, "Member 'FS_UniqueMechanic_Transform_Masks::MaskDescription_4_A41608594B3E8E3813C9B68E0CCD12A5' has a wrong offset!");

}

