#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FinishedGameCount

#include "Basic.hpp"

#include "WBP_FinishedGameCount_classes.hpp"
#include "WBP_FinishedGameCount_parameters.hpp"


namespace SDK
{

// Function WBP_FinishedGameCount.WBP_FinishedGameCount_C.SetFinishedGameCount
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InFinishedGameCount                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FinishedGameCount_C::SetFinishedGameCount(int32 InFinishedGameCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FinishedGameCount_C", "SetFinishedGameCount");

	Params::WBP_FinishedGameCount_C_SetFinishedGameCount Parms{};

	Parms.InFinishedGameCount = InFinishedGameCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FinishedGameCount.WBP_FinishedGameCount_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FinishedGameCount_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FinishedGameCount_C", "PreConstruct");

	Params::WBP_FinishedGameCount_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FinishedGameCount.WBP_FinishedGameCount_C.ExecuteUbergraph_WBP_FinishedGameCount
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FinishedGameCount_C::ExecuteUbergraph_WBP_FinishedGameCount(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FinishedGameCount_C", "ExecuteUbergraph_WBP_FinishedGameCount");

	Params::WBP_FinishedGameCount_C_ExecuteUbergraph_WBP_FinishedGameCount Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

