#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MM_TitleScreen

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.TransitionFromStart
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_TransitionFromStart final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_TransitionFromStart) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_TransitionFromStart");
static_assert(sizeof(WBP_MM_TitleScreen_C_TransitionFromStart) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_TransitionFromStart");
static_assert(offsetof(WBP_MM_TitleScreen_C_TransitionFromStart, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'WBP_MM_TitleScreen_C_TransitionFromStart::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.SetIsAnySave
// 0x0002 (0x0002 - 0x0000)
struct WBP_MM_TitleScreen_C_SetIsAnySave final
{
public:
	bool                                          IsAnySave;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInGamepadOrKeyboardNavigationMode_ReturnValue; // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_SetIsAnySave) == 0x000001, "Wrong alignment on WBP_MM_TitleScreen_C_SetIsAnySave");
static_assert(sizeof(WBP_MM_TitleScreen_C_SetIsAnySave) == 0x000002, "Wrong size on WBP_MM_TitleScreen_C_SetIsAnySave");
static_assert(offsetof(WBP_MM_TitleScreen_C_SetIsAnySave, IsAnySave) == 0x000000, "Member 'WBP_MM_TitleScreen_C_SetIsAnySave::IsAnySave' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_SetIsAnySave, CallFunc_IsInGamepadOrKeyboardNavigationMode_ReturnValue) == 0x000001, "Member 'WBP_MM_TitleScreen_C_SetIsAnySave::CallFunc_IsInGamepadOrKeyboardNavigationMode_ReturnValue' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_MM_TitleScreen_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_MM_TitleScreen_C_PreConstruct");
static_assert(sizeof(WBP_MM_TitleScreen_C_PreConstruct) == 0x000001, "Wrong size on WBP_MM_TitleScreen_C_PreConstruct");
static_assert(offsetof(WBP_MM_TitleScreen_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_MM_TitleScreen_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.ExecuteUbergraph_WBP_MM_TitleScreen
// 0x0120 (0x0120 - 0x0000)
struct WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPlatformsSubsystem*                    CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_wildcard_Variable;                            // 0x0018(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_wildcard_Variable_1;                          // 0x002C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_wildcard_Variable_2;                          // 0x003C(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_11;              // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_10;              // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_9;               // 0x0068(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_8;               // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBP_SaveManager_C*                      CallFunc_GetSaveManager_SaveManager;               // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_7;               // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAnySaveInAnySlot_ReturnValue;          // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_6;               // 0x0090(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Temp_wildcard_Variable_3;                          // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_5;               // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_4;               // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_3;               // 0x00B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_2;               // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x00D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCurrentPlatformConsole_CurrentPlatformIsConsole; // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           CallFunc_GetPlatformNameAsTag_ReturnValue;         // 0x00E4(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_GameplayTag_ReturnValue;       // 0x00EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x00ED(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x00EE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x00EF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_MakeLiteralText_ReturnValue;              // 0x00F0(0x0010)()
	class FText                                   CallFunc_MakeLiteralText_ReturnValue_1;            // 0x0100(0x0010)()
	class FText                                   K2Node_Select_Default_1;                           // 0x0110(0x0010)()
};
static_assert(alignof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen");
static_assert(sizeof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen) == 0x000120, "Wrong size on WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, EntryPoint) == 0x000000, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_bool_Variable) == 0x000004, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000010, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_wildcard_Variable) == 0x000018, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_wildcard_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_byte_Variable) == 0x000028, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_wildcard_Variable_1) == 0x00002C, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_wildcard_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_wildcard_Variable_2) == 0x00003C, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_wildcard_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_11) == 0x000050, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_11' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_10) == 0x000058, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_10' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_bool_Variable_1) == 0x000060, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_9) == 0x000068, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_9' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_8) == 0x000070, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_8' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_GetSaveManager_SaveManager) == 0x000078, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_GetSaveManager_SaveManager' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_7) == 0x000080, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_7' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_HasAnySaveInAnySlot_ReturnValue) == 0x000088, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_HasAnySaveInAnySlot_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_6) == 0x000090, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_6' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_wildcard_Variable_3) == 0x000098, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_wildcard_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_5) == 0x0000A8, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_5' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_4) == 0x0000B0, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_4' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_3) == 0x0000B8, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_3' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_2) == 0x0000C0, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_2' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button_1) == 0x0000C8, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_ComponentBoundEvent_Button) == 0x0000D0, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_PlayAnimation_ReturnValue_1) == 0x0000D8, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_IsCurrentPlatformConsole_CurrentPlatformIsConsole) == 0x0000E0, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_IsCurrentPlatformConsole_CurrentPlatformIsConsole' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_GetPlatformNameAsTag_ReturnValue) == 0x0000E4, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_GetPlatformNameAsTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_EqualEqual_GameplayTag_ReturnValue) == 0x0000EC, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_EqualEqual_GameplayTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, Temp_byte_Variable_1) == 0x0000ED, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_Select_Default) == 0x0000EE, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_Event_IsDesignTime) == 0x0000EF, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_MakeLiteralText_ReturnValue) == 0x0000F0, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_MakeLiteralText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, CallFunc_MakeLiteralText_ReturnValue_1) == 0x000100, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::CallFunc_MakeLiteralText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen, K2Node_Select_Default_1) == 0x000110, "Member 'WBP_MM_TitleScreen_C_ExecuteUbergraph_WBP_MM_TitleScreen::K2Node_Select_Default_1' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_11_OnButtonBaseUnfocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_SettingsButton_K2Node_ComponentBoundEvent_10_OnButtonBaseFocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_9_OnButtonBaseUnfocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_8_OnButtonBaseFocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_QuitButton_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_7_OnButtonBaseUnfocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_6_OnButtonBaseFocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_NewGameButton_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_5_OnButtonBaseUnfocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_4_OnButtonBaseFocused__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");
static_assert(sizeof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature) == 0x000008, "Wrong size on WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");
static_assert(offsetof(WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature, Button) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BndEvt__WBP_MM_TitleScreen_ContinueButton_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature::Button' has a wrong offset!");

// Function WBP_MM_TitleScreen.WBP_MM_TitleScreen_C.BP_GetDesiredFocusTarget
// 0x0018 (0x0018 - 0x0000)
struct WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_Select_Default;                             // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget) == 0x000008, "Wrong alignment on WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget");
static_assert(sizeof(WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget) == 0x000018, "Wrong size on WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget");
static_assert(offsetof(WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget, ReturnValue) == 0x000000, "Member 'WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget, Temp_bool_Variable) == 0x000008, "Member 'WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget, CallFunc_IsValid_ReturnValue) == 0x000009, "Member 'WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget, K2Node_Select_Default) == 0x000010, "Member 'WBP_MM_TitleScreen_C_BP_GetDesiredFocusTarget::K2Node_Select_Default' has a wrong offset!");

}

